name: Release

on:
  push:
    tags:
      - 'v*'

env:
  rgbds_version: v1.0.1

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout rgbds
        uses: actions/checkout@v6
        with:
          path: rgbds
          ref: ${{ env.rgbds_version }}
          repository: gbdev/rgbds

      - name: Install rgbds
        working-directory: rgbds
        run: |
          sudo apt-get update
          sudo apt-get install -yq bison libpng-dev pkg-config
          sudo make -j$(nproc) install

      - name: Remove rgbds
        run: |
          rm -rf rgbds

      - name: Build ROMs
        run: |
          make -j$(nproc)

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pokered.gbc
            pokeblue.gbc
          generate_release_notes: true
